### ISSUE TITLE
Enable closing the sidemenu also via horizontal swipe gesture option like facebook menu.

### ISSUE THREAD

**Issue by NSMutableString** [mikefrederick/MFSideMenu#52] opened 2013-03-07 12:31 UTC
Could come in handy. At this moment, they have to tap on the small section to close the menu.
I also use only one sideMenu at this moment.

**Comment by mikefrederick** [comment] 2013-03-13 12:09
I am closing this issue because I think it was a duplicate of https://github.com/mikefrederick/MFSideMenu/issues/54.

**Closed as completed by mikefrederick** 2013-03-13 12:09 UTC
